### PR TITLE
add place controller

### PR DESCRIPTION
**Pull request by smugikity**
no field "render_info" in creating / editing

### CODE REVIEW

**Comment by IP-13** [comment]
|Overall Project|66.98% **`-0.09%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|97.14%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[PlaceController.java](https://github.com/itmo-events-app/event-app/blob/11bc0e7ac90efcebcddc252d3533b565f30b66b1/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FPlaceController.java)|100%|:green_apple:|
|[PlaceService.java](https://github.com/itmo-events-app/event-app/blob/11bc0e7ac90efcebcddc252d3533b565f30b66b1/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FPlaceService.java)|96.19% **`-3.81%`**|:green_apple:|
|[TaskService.java](https://github.com/itmo-events-app/event-app/blob/11bc0e7ac90efcebcddc252d3533b565f30b66b1/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FTaskService.java)|89.09%|:green_apple:|

**Comment by IP-13** [comment]
|Overall Project|66.98% **`-0.09%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|97.14%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[PlaceController.java](https://github.com/itmo-events-app/event-app/blob/e601dafca3d71f08d1a74be534c0456dd87cc0ae/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FPlaceController.java)|100%|:green_apple:|
|[PlaceService.java](https://github.com/itmo-events-app/event-app/blob/e601dafca3d71f08d1a74be534c0456dd87cc0ae/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FPlaceService.java)|96.19% **`-3.81%`**|:green_apple:|
|[TaskService.java](https://github.com/itmo-events-app/event-app/blob/e601dafca3d71f08d1a74be534c0456dd87cc0ae/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FTaskService.java)|89.09%|:green_apple:|

**Comment by IP-13** [comment]
|Overall Project|66.98% **`-0.09%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|97.14%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[PlaceController.java](https://github.com/itmo-events-app/event-app/blob/3f4ff19c19607b4e54eab27ad1784550726f8694/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FPlaceController.java)|100%|:green_apple:|
|[PlaceService.java](https://github.com/itmo-events-app/event-app/blob/3f4ff19c19607b4e54eab27ad1784550726f8694/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FPlaceService.java)|96.19% **`-3.81%`**|:green_apple:|
|[TaskService.java](https://github.com/itmo-events-app/event-app/blob/3f4ff19c19607b4e54eab27ad1784550726f8694/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FTaskService.java)|89.09%|:green_apple:|

**Review by omgronny — APPROVED** [review]

**Comment by IP-13** [comment]
|Overall Project|71.65% **`-0.09%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|97.14%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[PlaceController.java](https://github.com/itmo-events-app/event-app/blob/cacc9380f5f7d552f85cc9206a39b125e0e05851/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FPlaceController.java)|100%|:green_apple:|
|[PlaceService.java](https://github.com/itmo-events-app/event-app/blob/cacc9380f5f7d552f85cc9206a39b125e0e05851/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FPlaceService.java)|96.19% **`-3.81%`**|:green_apple:|
|[TaskService.java](https://github.com/itmo-events-app/event-app/blob/cacc9380f5f7d552f85cc9206a39b125e0e05851/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FTaskService.java)|89.09%|:green_apple:|

**Review by IP-13 — APPROVED** [review]

**Pull request merged**
