### PR TITLE
Refactor privilege table

### PR DESCRIPTION
**Pull request by omgronny**

### CODE REVIEW

**Comment by omgronny** [comment]
@IP-13 @LiaoYihong-1 review pls

**Comment by IP-13** [comment]
|Overall Project|54.85%|:green_apple:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

**Comment by LiaoYihong-1** [comment]
Не понятно. Почему создать enum privilege_name в базе данных. Тип поля name в privilge - varchar.

**Comment by IP-13** [comment]
|Overall Project|54.85%|:green_apple:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

**Comment by IP-13** [comment]
|Overall Project|54.85%|:green_apple:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

**Comment by IP-13** [comment]
|Overall Project|54.85%|:green_apple:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

**Pull request closed without merging**
