### PR TITLE
Add list activities

### PR DESCRIPTION
**Pull request by omgronny**
- В запрос фильтрации мероприятий добавлен `parentId`, чтобы осуществлять фильтрацию активностей, либо только мероприятий

### CODE REVIEW

**Comment by IP-13** [comment]
|Overall Project|51.32%|:green_apple:|
|:-|:-|:-:|
|Files changed|100%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/322268e38c17b4303a1f1751ac63b967f55eb95f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/322268e38c17b4303a1f1751ac63b967f55eb95f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.51%|:green_apple:|

**Comment by IP-13** [comment]
|Overall Project|51.32%|:green_apple:|
|:-|:-|:-:|
|Files changed|100%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/14a3df126e68b3fff30e579631c3cc6fdb51d8ea/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/14a3df126e68b3fff30e579631c3cc6fdb51d8ea/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.51%|:green_apple:|

**Comment by IP-13** [comment]
|Overall Project|51.32%|:green_apple:|
|:-|:-|:-:|
|Files changed|100%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/96a72423f7c5b37af0d062b4ba4740f1c024c65f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/96a72423f7c5b37af0d062b4ba4740f1c024c65f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.51%|:green_apple:|

**Review by thermvs — APPROVED** [review]

**Comment by IP-13** [comment]
|Overall Project|51.66%|:green_apple:|
|:-|:-|:-:|
|Files changed|100%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/b5124a3705a1347bedd52f844b695fdb21d353d9/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/b5124a3705a1347bedd52f844b695fdb21d353d9/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.57%|:green_apple:|

**Comment by IP-13** [comment]
|Overall Project|51.66%|:green_apple:|
|:-|:-|:-:|
|Files changed|100%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/ee4a041a1f504b0257e205bcd9c99d8c8d792f67/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/ee4a041a1f504b0257e205bcd9c99d8c8d792f67/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.57%|:green_apple:|

**Comment by IP-13** [comment]
|Overall Project|51.66%|:green_apple:|
|:-|:-|:-:|
|Files changed|100%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/cca5faa852ac52efee935099a91f6f01a52b9450/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/cca5faa852ac52efee935099a91f6f01a52b9450/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.57%|:green_apple:|

**Comment by IP-13** [comment]
|Overall Project|51.66%|:green_apple:|
|:-|:-|:-:|
|Files changed|100%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/f5eeb134593f846372c2833c61ce9251b8f32b71/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/f5eeb134593f846372c2833c61ce9251b8f32b71/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.57%|:green_apple:|

**Comment by IP-13** [comment]
|Overall Project|51.66%|:green_apple:|
|:-|:-|:-:|
|Files changed|100%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/9d660c83aadb472cbd347249b9f91613dd050c7b/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/9d660c83aadb472cbd347249b9f91613dd050c7b/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.57%|:green_apple:|

**Review by LiaoYihong-1 — APPROVED** [review]

**Pull request merged**
